ARG IMG=nsenter
ARG TAG

FROM ${IMG}:${TAG} as builder

# Final image
FROM scratch

COPY --from=nsenter /code/util-linux/nsenter /
COPY --from=coreutils /code/coreutils/src/sleep /sleep

ENTRYPOINT ["/sleep"]
